name: Relase on pocketbase/release
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest pocketbase version
        id: pocketbase
        uses: muchobien/repo-releases@main
        with:
          repository: pocketbase/pocketbase
          excludes: draft,prerelease

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker-hub
        uses: docker/login-action@v2
        with:
          username: snwolak
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            snwolak/pocketbase
          tags: |
            type=semver,pattern={{version}},value=${{ steps.pocketbase.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: VERSION=${{ steps.pocketbase.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
